### ISSUE TITLE
Did this core work?

### ISSUE THREAD

**Issue by chepo92** [Daniel-dk/motionbow#1]
Hi @Daniel-dk 
 I know this is an old repo, but did you tested it? I want to use sam4 series with arduino so this would be a very good start point, at least it compiles ok in arduino, but I can't test it for now as can't find a 4S board near me

**Comment by chepo92** [comment]
Did a port for SAM4E based on this and it works :) 
https://github.com/chepo92/ArduinoCore-sam/tree/dev-SAM4E

**Comment by DanielRIOT** [comment]
Yep, This was for an old design we did to drive WS2811 LEDs, I still have a few of them lying around 
it works ok, but I have not ported it to the Arduino 1.1 api, 
teh USB part is based on teh work fdoen by FlutterWireless for the Sam3S ( same USB peripheral )
